version: '3.5'
networks:
  1_directly:
    driver: bridge
services:
  nginx:
    networks:
      - 1_directly
    container_name: 1directly-nginx
    image: bbtsoftwareag/nginx-proxy-unrestricted-requestsize:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  greeter_server:
    image: demo_nginx_grpc
    networks:
      - 1_directly
    ports:
      - "50051:50051"
    container_name: 1_directly-greeter_server
    hostname: greeter_server
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - nginx
    volumes:
      - "./1_directly:/code"
      - "./venv:/venv"
      - "./protos:/protos"
    command: /bin/bash -c "source /venv/bin/activate && python /code/src/greeter_server.py"
  greeter_client:
    image: demo_nginx_grpc
    networks:
      - 1_directly
    container_name: 1_directly-greeter_client
    hostname: greeter_client
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - nginx
      - greeter_server
    volumes:
      - "./1_directly:/code"
      - "./venv:/venv"
      - "./protos:/protos"
    command: /bin/bash -c "source /venv/bin/activate && python /code/src/greeter_client.py"